# Site settings
title: Xiangmin's Blog
SEOTitle: 李相民的博客 | Xiangmin's Blog
header-img: img/home-bg.jpg
email: li_xiangmin@qq.com
description: "这里是李相民的个人博客，记录游戏开发的思考与实践 | 心有所向, 日复一日, 必有精进!"
keyword: "李相民, 独立开发者, Unity, 游戏开发, C#, 技术博客, 独立游戏,"
url: "https://Xiangmin-Li.github.io"
baseurl: ""

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
#weibo_username:
#zhihu_username:
github_username: Xiangmin-Li
#twitter_username:
#facebook_username:
#linkedin_username:

# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true

#timezone: Asia/Shanghai

# Gems
plugins: [jekyll-paginate]

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username:

# Netease settings
netease_comment: false

# Analytics settings
# ga_track_id: [填写你自己的]
# ga_domain: xiangmin-li.github.io

# Sidebar settings
sidebar: true
sidebar-about-description: "心有所向, 日复一日, 必有精进!"
sidebar-avatar: https://github.com/Xiangmin-Li.png # 如果你有 GitHub 头像，这个链接是可用的

# Featured Tags
featured-tags: false
# featured-condition-size: 1

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page
page-mathjax: false

# Friends
friends:
  [
   # { title: "OpenAI", href: "https://openai.com" },
   # { title: "Unity", href: "https://unity.com" },
   # { title: "知乎 - 游戏设计", href: "https://www.zhihu.com/topic/19555428" }
  ]
